"use client";

import { GridStyleSimulationSection, type GridStyleSimulationConfig } from "@/components/simulations/grid-dataops-simulator-section";

const afterboardsConfig: GridStyleSimulationConfig = {
  title: "Afterboards CUET/IPMAT - Simulacrum Ad Evaluation",
  metaLine: "single · 10.0K agents · 52.0s · 10 archetypes · 88.0% confidence",
  overallScoreLabel: "Overall: 88/100",
  kpis: [
    { label: "Simulacrum Engagement", value: "88/100" },
    { label: "Cognitive Load", value: "13.4 ms" },
    { label: "Trust Retention Rate", value: "92%" },
    { label: "Conversion Probability (p)", value: "0.85" },
  ],
  secondaryStats: [
    { label: "Audience Resonance", value: "94%" },
    { label: "Virality Coefficient", value: "1.2" },
    { label: "Information Density", value: "85%" },
  ],
  video: {
    src: "/afterboards-test.mp4",
    duration: 52,
    predictionKey: "afterboards-test.predictions",
    maxSegment: 51,
  },
  brainFooter: {
    simulatedReach: "10.0K",
    peakAttention: "94%",
  },
  agentJourneys: [
    {
      name: "Aryan",
      age: 20,
      gender: "male",
      outcome: "high intent",
      description: "Skeptical about EdTech ads, converted after seeing no-login proof and UI walkthrough.",
      exp: 13,
      confidence: "89.0%",
      keyTrigger: "No-login claim verified on screen at 0:28",
      journey: [
        { day: 1, note: "Almost swiped, but the anti-NTA opener felt unusually real.", tags: ["hooked"] },
        { day: 3, note: "Rewatched from 0:23 to confirm the product reveal wasn't bait.", tags: ["verifying"], actions: ["replayed demo"] },
        { day: 5, note: "Paused on the site section to check if no-login was actually true.", tags: ["skeptical"] },
        { day: 7, note: "Noticed clean UI and no fake urgency popups.", tags: ["trust gain"] },
        { day: 10, note: "Shared to one friend and asked if they had used Afterboards before.", tags: ["social proof"], actions: ["sent to friend"] },
        { day: 12, note: "Friend confirmed it works for PYP practice; confidence improved.", tags: ["validated"] },
        { day: 14, note: "Saved the reel for weekend revision setup.", tags: ["warming up"], actions: ["saved"] },
        { day: 16, note: "Commented 'PYP' and requested link.", tags: ["action"], actions: ["commented CTA"] },
        { day: 18, note: "Moved to high intent after trying the first mock flow.", tags: ["high intent"], actions: ["tested mock"] },
      ],
    },
    {
      name: "Kavya",
      age: 19,
      gender: "female",
      outcome: "high intent",
      description: "High exam anxiety; resonates with the frustration framing and immediately acts on PYP CTA.",
      exp: 12,
      confidence: "93.0%",
      keyTrigger: "NTA frustration + instant PYP utility",
      journey: [
        { day: 1, note: "The 'scattered resources' pain is exactly my daily situation.", tags: ["seen"] },
        { day: 2, note: "Watched again and focused on topic-wise navigation.", tags: ["curious"] },
        { day: 4, note: "Compared it with Telegram dumps and still preferred this flow.", tags: ["evaluating"] },
        { day: 6, note: "The no-login step removed my usual hesitation.", tags: ["friction removed"] },
        { day: 8, note: "Saved for later because I had coaching homework.", tags: ["intent"], actions: ["saved"] },
        { day: 11, note: "Reopened and checked if IPMAT sections were also organized.", tags: ["qualification"] },
        { day: 13, note: "Commented 'PYP' to get the direct link.", tags: ["action"], actions: ["commented CTA"] },
        { day: 15, note: "Started first targeted test by topic.", tags: ["adopted"], actions: ["attempted topic test"] },
      ],
    },
    {
      name: "Rohan",
      age: 22,
      gender: "male",
      outcome: "high intent",
      description: "Responds strongly to the anti-data-harvesting narrative ('Janam Kundli' callout).",
      exp: 15,
      confidence: "90.0%",
      keyTrigger: "Competitor privacy critique (parents' numbers / over-collection)",
      journey: [
        { day: 1, note: "The 'Janam Kundli' line instantly resonated with my privacy concerns.", tags: ["resonance"] },
        { day: 3, note: "Looked for hidden signup traps in comments and landing behavior.", tags: ["auditing"] },
        { day: 5, note: "No forced phone-number gate improved trust strongly.", tags: ["trust gain"] },
        { day: 8, note: "Compared with two coaching portals that asked for parent contacts.", tags: ["benchmarking"] },
        { day: 10, note: "Sent reel to my study circle as a safer prep option.", tags: ["advocacy"], actions: ["shared post"] },
        { day: 13, note: "Observed peers confirming the workflow is genuinely open.", tags: ["social proof"] },
        { day: 16, note: "Commented for link and started using it for quick revision pulls.", tags: ["adopted"], actions: ["commented CTA"] },
      ],
    },
    {
      name: "Ishan",
      age: 21,
      gender: "male",
      outcome: "considering",
      description: "Loves fast pacing but finds URL reveal too abrupt; wants clearer save mechanic.",
      exp: 14,
      confidence: "61.0%",
      keyTrigger: "High-speed delivery with minor discoverability friction",
      journey: [
        { day: 1, note: "Loved the pace; zero filler in the first half.", tags: ["efficient"] },
        { day: 2, note: "Transition to screen recording felt abrupt and dense.", tags: ["friction"] },
        { day: 4, note: "Had to pause multiple times to catch the exact website name.", tags: ["discoverability"], actions: ["paused video"] },
        { day: 6, note: "Still impressed with organization depth once I found the flow.", tags: ["value"] },
        { day: 9, note: "Would prefer pinned keyword comment plus save prompt.", tags: ["ux suggestion"] },
        { day: 12, note: "Revisited post from saved tab but link retrieval took extra effort.", tags: ["considering"], actions: ["reopened saved post"] },
        { day: 15, note: "Converted after comment response came quickly.", tags: ["converted"], actions: ["commented CTA"] },
      ],
    },
    {
      name: "Meera",
      age: 23,
      gender: "female",
      outcome: "considering",
      description: "Trusts UGC authenticity but flags glare and shaky footage hurting readability.",
      exp: 11,
      confidence: "56.0%",
      keyTrigger: "Authentic tone vs. visual polish tradeoff",
      journey: [
        { day: 1, note: "Raw room setup made it feel authentic, not studio-scripted.", tags: ["authentic"] },
        { day: 3, note: "Glare on screen reduced readability of difficulty tags.", tags: ["readability issue"] },
        { day: 5, note: "Liked the no-BS narration style despite visual noise.", tags: ["tone fit"] },
        { day: 7, note: "Expected cleaner crop-in shots during product demo section.", tags: ["production gap"] },
        { day: 10, note: "Saved because utility seemed strong enough to tolerate rough visuals.", tags: ["soft intent"], actions: ["saved"] },
        { day: 13, note: "Revisited and focused only on mock feature walkthrough.", tags: ["evaluating"] },
        { day: 16, note: "Still considering; would convert immediately with clearer v2 edit.", tags: ["conditional"] },
      ],
    },
    {
      name: "Shreya",
      age: 20,
      gender: "female",
      outcome: "high intent",
      description: "Highly sensitive to signup friction; 'free + no login' produces immediate trust.",
      exp: 10,
      confidence: "94.0%",
      keyTrigger: "Free access without phone-number gate",
      journey: [
        { day: 1, note: "Free + no login removed my biggest trust barrier instantly.", tags: ["relief"] },
        { day: 2, note: "Rewatched to verify no hidden paywall cues.", tags: ["verifying"] },
        { day: 4, note: "Compared with two portals that locked PDFs behind signup.", tags: ["comparison"] },
        { day: 6, note: "Shared with roommate who also prepares CUET.", tags: ["social"], actions: ["shared"] },
        { day: 9, note: "Saved for weekend test planning.", tags: ["intent"], actions: ["saved"] },
        { day: 12, note: "Commented PYP, got link, and started practice flow.", tags: ["action"], actions: ["commented CTA"] },
        { day: 15, note: "Now using topic mocks regularly before coaching sessions.", tags: ["adopted"] },
      ],
    },
    {
      name: "Arjun",
      age: 18,
      gender: "male",
      outcome: "considering",
      description: "Values product utility but struggles with fast Hinglish and slang density.",
      exp: 9,
      confidence: "52.0%",
      keyTrigger: "Needs slower captions and clearer on-screen anchors",
      journey: [
        { day: 1, note: "First watch was too fast; missed several spoken points.", tags: ["overwhelmed"] },
        { day: 3, note: "Second watch with manual pauses improved understanding.", tags: ["coping"], actions: ["paused video"] },
        { day: 5, note: "Math labels on screen helped anchor meaning.", tags: ["partial comprehension"] },
        { day: 7, note: "Still unsure about all CTA instructions in rapid Hinglish.", tags: ["friction"] },
        { day: 10, note: "Asked a friend to explain final CTA sequence.", tags: ["support needed"], actions: ["asked peer"] },
        { day: 13, note: "Saved post and waited for text-based summary in comments.", tags: ["considering"], actions: ["saved"] },
        { day: 17, note: "Would convert with subtitles and slower feature narration.", tags: ["accessibility need"] },
      ],
    },
    {
      name: "Aditya",
      age: 22,
      gender: "male",
      outcome: "high intent",
      description: "Understands CTA is engagement-engineered, but accepts it because value is real.",
      exp: 12,
      confidence: "87.0%",
      keyTrigger: "Comment loop is acceptable when utility is genuine",
      journey: [
        { day: 1, note: "Spotted the engagement-loop CTA pattern immediately.", tags: ["aware"] },
        { day: 2, note: "Checked if product value justified the comment gate.", tags: ["skeptical"] },
        { day: 4, note: "UI demo quality convinced me this wasn't pure bait.", tags: ["rational trust"] },
        { day: 7, note: "Monitored comment section response speed.", tags: ["testing mechanic"] },
        { day: 9, note: "Saw consistent link sharing behavior from creator.", tags: ["validated"] },
        { day: 12, note: "Commented PYP and entered workflow.", tags: ["action"], actions: ["commented CTA"] },
        { day: 14, note: "Shared as a rare case where growth loop and value both exist.", tags: ["advocacy"], actions: ["shared post"] },
      ],
    },
    {
      name: "Ananya",
      age: 24,
      gender: "female",
      outcome: "considering",
      description: "Likes clean product surface, but wants stronger emphasis on 'Attempt Mock' stickiness.",
      exp: 16,
      confidence: "63.0%",
      keyTrigger: "Feature prioritization in storytelling",
      journey: [
        { day: 1, note: "Immediate positive impression on IA and clean information layout.", tags: ["positive UX"] },
        { day: 3, note: "Narrative over-indexed on rant vs. product walkthrough time.", tags: ["story imbalance"] },
        { day: 6, note: "Mock feature looked strong but was under-demonstrated.", tags: ["feature gap"] },
        { day: 9, note: "Expected one concrete 'attempt mock now' task path in-video.", tags: ["ux recommendation"] },
        { day: 12, note: "Saved for a deeper product trial later.", tags: ["considering"], actions: ["saved"] },
        { day: 15, note: "Revisited and found real utility despite narrative imbalance.", tags: ["value confirmed"] },
        { day: 18, note: "Would upgrade intent with clearer flow framing in edit v2.", tags: ["conditional"] },
      ],
    },
    {
      name: "Tanvi",
      age: 19,
      gender: "female",
      outcome: "high intent",
      description: "Emotionally reassured by anti-coaching pressure narrative; anxiety drops after solution reveal.",
      exp: 12,
      confidence: "91.0%",
      keyTrigger: "Emotional validation + low-friction actionable shortcut",
      journey: [
        { day: 1, note: "Felt emotionally seen by the coaching-pressure callout.", tags: ["emotional match"] },
        { day: 2, note: "Rewatched because tone felt like a peer, not a seller.", tags: ["trust"] },
        { day: 4, note: "Solution reveal reduced overwhelm significantly.", tags: ["relief"] },
        { day: 6, note: "Saved reel for post-class revision planning.", tags: ["intent"], actions: ["saved"] },
        { day: 9, note: "Shared with one friend who also struggles with scattered prep.", tags: ["community"], actions: ["shared"] },
        { day: 12, note: "Commented PYP and received link.", tags: ["action"], actions: ["commented CTA"] },
        { day: 15, note: "Completed first mock and felt more in control of preparation.", tags: ["high intent"], actions: ["attempted mock"] },
      ],
    },
  ],
  recommendations: {
    budget: [],
    creative: [
      "Add on-screen subtitles and slightly slower delivery in the first 20s to reduce language-barrier drop-off.",
      "Stabilize and brighten the screen-recording segment so topic and difficulty tags are readable on first pass.",
      "Give the 'Attempt Mock' flow 3-5 extra seconds; this is the strongest retention feature and should be more explicit.",
      "Keep the anti-friction messaging ('Free', 'No Login') prominent since it drives trust and conversion intent.",
      "Add a 'Save this for revision' micro-CTA before final comment CTA to capture high-intent users who are not ready to comment yet.",
    ],
  },
  hideEmotionalArousal: true,
  hideDesireAida: true,
};

export function AfterboardsSimulatorSection() {
  return <GridStyleSimulationSection config={afterboardsConfig} />;
}

