"use client";

import { GridStyleSimulationSection, type GridStyleSimulationConfig } from "@/components/simulations/grid-dataops-simulator-section";

const afterboardsCuetIpmat2026Config: GridStyleSimulationConfig = {
  title: "Afterboards 2026: High-Intent UGC Prototype",
  metaLine: "single · 10.0K agents · 35.0s · 10 archetypes · 88.0% confidence",
  overallScoreLabel: "Overall: 88/100",
  kpis: [
    { label: "Clicks", value: "5,877" },
    { label: "CTR", value: "1.41%" },
    { label: "Impr.", value: "416,775" },
    { label: "Cost", value: "₹38,691.41" },
  ],
  secondaryStats: [
    { label: "Audience Resonance", value: "92%" },
  ],
  video: {
    src: "/afterboards-35s-test3.mp4",
    duration: 35,
    predictionKey: "afterboards-35s-test3.predictions",
    maxSegment: 35,
    aspectRatio: "16/9",
  },
  brainFooter: {
    simulatedReach: "416,775",
    peakAttention: "5,877",
    simulatedReachLabel: "Impressions",
    peakAttentionLabel: "Clicks",
  },
  hideMetaLine: true,
  hideDeepSimulationChip: true,
  hideExportButton: true,
  agentJourneys: [
    {
      name: "Liam",
      age: 19,
      gender: "male",
      outcome: "high intent",
      description: "Captivated by the 'this is ad' hook. Converted after seeing the dictionary demo and real SWOT analysis.",
      exp: 14,
      confidence: "91.0%",
      keyTrigger: "Clear utility demo (word lookup + SWOT)",
      journey: [
        { day: 1, note: "The 'this is ad' hook actually made me stop and watch.", tags: ["hooked"] },
        { day: 4, note: "Interface demo shows this is a real, working product.", tags: ["trust gain"] },
        { day: 7, note: "Direct word lookup feature solves my biggest pain point.", tags: ["utility"] },
        { day: 10, note: "Rewatched the SWOT section to understand the data logic.", tags: ["verifying"] },
        { day: 14, note: "Saved the video to test it out during the weekend.", tags: ["intent"], actions: ["saved"] },
        { day: 17, note: "Shared with a study buddy to get their opinion.", tags: ["social proof"], actions: ["shared"] },
        { day: 20, note: "Commented for the link and started the first mock test.", tags: ["action"], actions: ["commented CTA"] },
      ],
    },
    {
      name: "Emma",
      age: 20,
      gender: "female",
      outcome: "high intent",
      description: "Prioritized the no-login and error-free claims. Adopted after confirming 2026 syllabus updates.",
      exp: 12,
      confidence: "89.0%",
      keyTrigger: "Error-free + no-friction onboarding",
      journey: [
        { day: 1, note: "The promise of an error-free prep tool is exactly what I need.", tags: ["curious"] },
        { day: 5, note: "Rewatched to verify if the 2026 syllabus was truly integrated.", tags: ["verifying"] },
        { day: 9, note: "Comparing the topic-wise breakdown with my current coaching notes.", tags: ["benchmarking"] },
        { day: 13, note: "No-login step removes my usual privacy hesitation.", tags: ["trust gain"] },
        { day: 18, note: "Converted because the flow is fast and requires minimal effort.", tags: ["friction removed"] },
        { day: 22, note: "Commented for the link and started practicing by topic.", tags: ["adopted"], actions: ["commented CTA"] },
      ],
    },
    {
      name: "Noah",
      age: 21,
      gender: "male",
      outcome: "considering",
      description: "Appreciated the value framing but felt the price/URL segment was too fast to catch.",
      exp: 11,
      confidence: "63.0%",
      keyTrigger: "Strong value framing but short CTA exposure",
      journey: [
        { day: 1, note: "Content is solid; the video pace is fast and clear.", tags: ["positive"] },
        { day: 5, note: "The price and URL at the end flashed by a bit too quickly.", tags: ["discoverability issue"] },
        { day: 10, note: "Saved it anyway because the utility seems very high.", tags: ["soft intent"], actions: ["saved"] },
        { day: 14, note: "Checking comments to see if others found the direct link.", tags: ["research"] },
        { day: 18, note: "Waiting for a clearer look at the CTA before final conversion.", tags: ["considering"] },
      ],
    },
    {
      name: "Olivia",
      age: 18,
      gender: "female",
      outcome: "high intent",
      description: "Resonated with the authentic lo-fi style. Felt it was more trustworthy than polished studio ads.",
      exp: 10,
      confidence: "90.0%",
      keyTrigger: "Social authenticity",
      journey: [
        { day: 1, note: "The face-to-camera talk feels real and relatable.", tags: ["authentic"] },
        { day: 3, note: "SWOT demo clarifies the learning value beyond just hype.", tags: ["value"] },
        { day: 7, note: "Liked the 'no-BS' attitude of the creator.", tags: ["tone match"] },
        { day: 11, note: "Shared it with my friends preparing for CUET.", tags: ["social proof"], actions: ["shared"] },
        { day: 15, note: "Saved to my revision playlist for later use.", tags: ["intent"], actions: ["saved"] },
        { day: 19, note: "Revisited the post to check for link updates in comments.", tags: ["returning"] },
        { day: 22, note: "Commented for the link and jumped in immediately.", tags: ["high intent"], actions: ["commented CTA"] },
        { day: 25, note: "First practice session completed; dashboard feels intuitive.", tags: ["success"], actions: ["completed mock"] },
      ],
    },
    {
      name: "James",
      age: 22,
      gender: "male",
      outcome: "considering",
      description: "Understood product value but struggled with small text readability on mobile.",
      exp: 9,
      confidence: "58.0%",
      keyTrigger: "Readability on small screen",
      journey: [
        { day: 1, note: "Great hook, but the pricing text is hard to read on a small screen.", tags: ["readability"] },
        { day: 4, note: "Rewatched and paused to make sure I got all the info.", tags: ["friction"], actions: ["paused video"] },
        { day: 8, note: "Interface looks clean but needs better contrast for labels.", tags: ["ux feedback"] },
        { day: 12, note: "Still rate the utility of the feature demo very highly.", tags: ["value"] },
        { day: 15, note: "Will convert if I can see clearer subtitles in the next version.", tags: ["conditional"] },
      ],
    },
    {
      name: "Sophia",
      age: 19,
      gender: "female",
      outcome: "high intent",
      description: "Highly focused on the instant dictionary feature. Responds well to the peer-to-peer tone.",
      exp: 13,
      confidence: "92.0%",
      keyTrigger: "Peer-to-peer trust + utility",
      journey: [
        { day: 1, note: "The creator sounds like a student who actually uses this.", tags: ["trust"] },
        { day: 4, note: "Instant dictionary is a game changer for my reading practice.", tags: ["utility"] },
        { day: 7, note: "Comparing this with my current vocabulary apps.", tags: ["benchmarking"] },
        { day: 10, note: "Saved to my 'Study Hacks' collection.", tags: ["intent"], actions: ["saved"] },
        { day: 13, note: "Shared with my tutoring group for feedback.", tags: ["social validation"], actions: ["shared"] },
        { day: 16, note: "Rewatched the no-login proof at 0:25.", tags: ["verifying"] },
        { day: 19, note: "Commented for link and received instant response.", tags: ["action"], actions: ["commented CTA"] },
        { day: 21, note: "Started using the SWOT feature for targeted revision.", tags: ["active"], actions: ["tested SWOT"] },
        { day: 24, note: "Confidence in CUET prep improved by 15%.", tags: ["impact"] },
      ],
    },
    {
      name: "William",
      age: 20,
      gender: "male",
      outcome: "high intent",
      description: "Looking for 2026 syllabus alignment. Convinced by the topic-wise breakdown demo.",
      exp: 11,
      confidence: "88.0%",
      keyTrigger: "Topic-wise organization",
      journey: [
        { day: 1, note: "Scattered prep material is my biggest stressor right now.", tags: ["pain point"] },
        { day: 4, note: "The topic-wise breakdown in the demo looks very organized.", tags: ["value"] },
        { day: 8, note: "Verified that the logical reasoning topics are up to date.", tags: ["verifying"] },
        { day: 12, note: "No login requirement makes it easy to try out.", tags: ["frictionless"] },
        { day: 15, note: "Commented for access and began the logical reasoning mock.", tags: ["action"], actions: ["commented CTA"] },
        { day: 19, note: "Highly satisfied with the depth of the mock question bank.", tags: ["adopted"] },
      ],
    },
    {
      name: "Isabella",
      age: 21,
      gender: "female",
      outcome: "considering",
      description: "Likes the no-BS approach but finds the transition to the screen recording too fast.",
      exp: 14,
      confidence: "65.0%",
      keyTrigger: "Authentic narrative vs technical transition",
      journey: [
        { day: 1, note: "Love the raw energy and honest 'this is ad' opening.", tags: ["positive tone"] },
        { day: 4, note: "Technical transition was a bit jerky; had to rewatch.", tags: ["technical friction"] },
        { day: 7, note: "Checked the creator's profile for more product demos.", tags: ["investigating"] },
        { day: 11, note: "Product looks superior to existing coaching portals.", tags: ["comparison"] },
        { day: 15, note: "Saved for later; might convert if the link is easy to find.", tags: ["considering"], actions: ["saved"] },
        { day: 18, note: "Noticed a detailed breakdown in the comments section.", tags: ["trust gain"] },
        { day: 21, note: "Would convert if the transition to screen capture was smoother.", tags: ["ux barrier"] },
      ],
    },
    {
      name: "Lucas",
      age: 22,
      gender: "male",
      outcome: "high intent",
      description: "Data-driven prep student. Resonated with the error-free and updated syllabus claims.",
      exp: 12,
      confidence: "87.0%",
      keyTrigger: "Reliability of content",
      journey: [
        { day: 1, note: "Need a reliable source for 2026 mocks. This looks promising.", tags: ["seeking"] },
        { day: 5, note: "The SWOT feature helps prioritize my weak areas efficiently.", tags: ["utility"] },
        { day: 9, note: "Shared with my study group to see if they like the UI.", tags: ["validation"], actions: ["shared"] },
        { day: 13, note: "Re-evaluated against a popular competitor's mobile app.", tags: ["benchmarking"] },
        { day: 17, note: "Received the link via comment and set up my dashboard.", tags: ["adopted"], actions: ["commented CTA"] },
      ],
    },
    {
      name: "Mia",
      age: 19,
      gender: "female",
      outcome: "high intent",
      description: "Emotionally driven but utility-focused. The peer-led narration style won her over.",
      exp: 10,
      confidence: "91.0%",
      keyTrigger: "Peer-led narration style",
      journey: [
        { day: 1, note: "Feels like I'm getting advice from a senior, not a company.", tags: ["emotional trust"] },
        { day: 4, note: "The dictionary feature is exactly what I was looking for.", tags: ["utility match"] },
        { day: 8, note: "No forced signup is a huge plus for me.", tags: ["trust gain"] },
        { day: 11, note: "Shared the reel on my story to help others.", tags: ["advocacy"], actions: ["shared"] },
        { day: 15, note: "Saved it to revisit when I start my English revision block.", tags: ["intent"], actions: ["saved"] },
        { day: 18, note: "Rewatched the demo to confirm difficulty tag accuracy.", tags: ["verifying"] },
        { day: 21, note: "Commented 'link' and immediately tried the first mock test.", tags: ["action"], actions: ["commented CTA"] },
        { day: 23, note: "Successfully integrated the tool into my daily study routine.", tags: ["success"] },
      ],
    },
  ],
  recommendations: {
    budget: [],
    creative: [
      "Keep the 'this is ad' opening as it successfully disrupts ad blindness.",
      "Increase the font size for pricing and URL in the final segment to improve recall.",
      "Add subtitles to the feature demo section to reduce drop-off from fast narration.",
      "Extend the final CTA screen by 2-3 seconds to allow more processing time.",
      "Test a dark mode UI variant to see its impact on focus for late-night study sessions.",
    ],
  },
  hideEmotionalArousal: true,
  hideDesireAida: true,
};

export function AfterboardsCuetIpmat2026SimulatorSection() {
  return <GridStyleSimulationSection config={afterboardsCuetIpmat2026Config} />;
}